name: Daily Screenshot Test (Mays Paving)

on:
  workflow_dispatch:

jobs:
  single_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright + browsers
        run: |
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Screenshot Mays Paving
        id: shot
        env:
          SHOT_URLS: "https://www.mayspaving.com/"
        shell: bash
        run: |
          set -e
          mkdir -p shots
          echo "Taking screenshot of $SHOT_URLS"
          python scripts/daily_screenshot.py
          shopt -s nullglob
          files=(shots/*.jpg shots/*.jpeg)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No screenshot found, skipping email."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "file=${files[0]}" >> "$GITHUB_OUTPUT"
            echo "Saved: ${files[0]}"
          fi

      - name: Email Screenshot
        if: ${{ steps.shot.outputs.skip != 'true' && steps.shot.outputs.file != '' }}
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          URL_UNDER_TEST: "https://www.mayspaving.com/"
          SHOT_FILE: ${{ steps.shot.outputs.file }}
        shell: bash
        run: |
          python - <<'PY'
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

# Get environment variables
server = os.environ["SMTP_SERVER"]
port = int(os.environ["SMTP_PORT"])
user = os.environ["SMTP_USERNAME"]
pw = os.environ["SMTP_PASSWORD"]
frm = os.environ["FROM_EMAIL"]
to = os.environ["TO_EMAIL"]
url = os.environ["URL_UNDER_TEST"]
shot = os.environ.get("SHOT_FILE")

# Validate screenshot file exists
if not shot or not os.path.exists(shot):
    raise SystemExit("SHOT_FILE missing or not found; nothing to send.")

# Create email message
msg = MIMEMultipart("related")
msg["Subject"] = f"[Screenshot Test] {url}"
msg["From"] = frm
msg["To"] = to

# Create alternative part for plain text and HTML
alt = MIMEMultipart("alternative")
alt.attach(MIMEText(f"Screenshot for {url}", "plain"))
alt.attach(MIMEText(
    f"<p>Screenshot for <b>{url}</b>:</p>"
    f"<img src='cid:screenshot' style='max-width:100%;height:auto;'>",
    "html"
))
msg.attach(alt)

# Attach screenshot image
with open(shot, "rb") as f:
    img = MIMEImage(f.read())
img.add_header("Content-ID", "<screenshot>")
img.add_header("Content-Disposition", "inline", filename=os.path.basename(shot))
msg.attach(img)

# Send email
ctx = ssl.create_default_context()
if port == 465:
    with smtplib.SMTP_SSL(server, port, context=ctx) as s:
        s.login(user, pw)
        s.sendmail(frm, [to], msg.as_string())
else:
    with smtplib.SMTP(server, port) as s:
        s.starttls(context=ctx)
        s.login(user, pw)
        s.sendmail(frm, [to], msg.as_string())

print(f"Sent screenshot for {url} → {to} ({shot})")
PY
