name: Daily Site Screenshots (One email per URL)

on:
  schedule:
    - cron: "5 11 * * *"
  workflow_dispatch: {}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.collect.outputs.urls }}
    steps:
      - uses: actions/checkout@v4
      - id: collect
        run: |
          if [ -n "${{ secrets.SHOT_URLS }}" ]; then
            RAW="${{ secrets.SHOT_URLS }}"
            echo "urls=$(printf '%s' "$RAW" | awk -v RS=, 'NF{gsub(/^[ \t]+|[ \t]+$/,""); printf "%s\"%s\"", (NR==1?"[":","), $0} END{print "]"}')" >> $GITHUB_OUTPUT
          else
            sudo apt-get update && sudo apt-get install -y jq
            echo "urls=$(jq -c . urls.json)" >> $GITHUB_OUTPUT
          fi

  shoot_and_email:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        url: ${{ fromJSON(needs.prepare.outputs.urls) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright + browsers
        run: |
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Screenshot one URL to JPEG
        env:
          SHOT_URLS: ${{ matrix.url }}
        run: |
          python scripts/daily_screenshot.py
          # pick the single file we just created and expose it as SHOT_FILE
          f=$(ls -1 shots/*.jpg | head -n1)
          echo "SHOT_FILE=$f" >> $GITHUB_ENV
          echo "Using file: $f"

      - name: Send email with this one attachment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: true
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          subject: "[Site Screenshot] ${{ matrix.url }} - ${{ github.run_id }}"
          html_body: |
            <p>Hi Darren,</p>
            <p>Today's screenshot for <b>${{ matrix.url }}</b> is attached.</p>
            <p>Run: ${{ github.run_id }} • UTC: ${{ github.run_started_at }}</p>
          attachments: ${{ env.SHOT_FILE }}
